In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import seaborn as sns

from glob import glob

In [6]:
# Extract path
female_path = glob('../cropped_faces/females/*.jpg')
male_path = glob('../cropped_faces/males/*.jpg')

In [7]:
# Create one data frame
df_female = pd.DataFrame(female_path, columns = ['filepath'])
df_female['gender'] = 'female'
df_male = pd.DataFrame(male_path, columns = ['filepath'])
df_male['gender'] = 'male'

faces_dataframe = pd.concat((df_female, df_male), axis=0)

In [8]:
faces_dataframe.head()

                                      filepath  gender
0     ../cropped_faces/females\females_0_0.jpg  female
1     ../cropped_faces/females\females_0_1.jpg  female
2  ../cropped_faces/females\females_1000_0.jpg  female
3  ../cropped_faces/females\females_1001_0.jpg  female
4  ../cropped_faces/females\females_1002_0.jpg  female

In [9]:
faces_dataframe.tail()

                                    filepath gender
3715  ../cropped_faces/males\males_994_0.jpg   male
3716  ../cropped_faces/males\males_995_0.jpg   male
3717  ../cropped_faces/males\males_996_0.jpg   male
3718  ../cropped_faces/males\males_998_0.jpg   male
3719    ../cropped_faces/males\males_9_0.jpg   male

In [12]:
faces_dataframe.shape

(7663, 2)

In [14]:
# Get the images width as size of the of the image
def get_size(img_path):
    img = cv2.imread(img_path)
    return img.shape[0]

In [15]:
# Store dimensions of image in columns 
faces_dataframe['dimension'] = faces_dataframe['filepath'].apply(get_size)